// Generated by kde/tools/gen_editor_themes.py from KDE syntax-highlighting v6.30.0 (data/themes, MIT). Do not edit.
// Colours only; token colours come from the library's own theme of the same name. Copyright:
//   Breeze Light: 2016 Volker Krause <vkrause@kde.org>; 2016 Dominik Haumann <dhaumann@kde.org>
//   Breeze Dark: 2016 Volker Krause <vkrause@kde.org>; 2016 Dominik Haumann <dhaumann@kde.org>
//   Atom One Light: 2016 GitHub Inc.; 2020 Waqar Ahmed <waqar.17a@gmail.com>
//   Atom One Dark: 2016 GitHub Inc.; 2020 Waqar Ahmed <waqar.17a@gmail.com>
//   Catppuccin Latte: 2021 Catppuccin Org
//   Catppuccin Mocha: 2021 Catppuccin Org
//   GitHub Light: 2020 GitHub Inc.; 2020 Waqar Ahmed <waqar.17a@gmail.com>
//   GitHub Dark: 2020 GitHub Inc.; 2020 Waqar Ahmed <waqar.17a@gmail.com>
//   Solarized Light: 2011 Ethan Schoonover; 2012 Dominik Haumann <dhaumann@kde.org>; 2018 Andrew Crouthamel <andrew.crouthamel@kdemail.net>
//   Solarized Dark: 2011 Ethan Schoonover; 2012 Dominik Haumann <dhaumann@kde.org>; 2018 Andrew Crouthamel <andrew.crouthamel@kdemail.net>
import QtQuick

QtObject {
    readonly property var themes: ({
        "Breeze Light": {
                "background": "#ffffff",
                "text": "#1f1c1b",
                "selectedText": "#ffffff",
                "selection": "#94caef",
                "lineNumber": "#a0a0a0",
                "heading": "#644a9b",
                "code": "#b08000",
                "link": "#006e28",
                "quote": "#0057ae",
                "codeBackground": "#f8f7f6"
        },
        "Breeze Dark": {
                "background": "#232629",
                "text": "#cfcfc2",
                "selectedText": "#cfcfc2",
                "selection": "#2d5c76",
                "lineNumber": "#7a7c7d",
                "heading": "#8e44ad",
                "code": "#c45b00",
                "link": "#27ae60",
                "quote": "#2980b9",
                "codeBackground": "#2A2E32"
        },
        "Atom One Light": {
                "background": "#fafafa",
                "text": "#383a42",
                "selectedText": "#383a42",
                "selection": "#e5e5e6",
                "lineNumber": "#9D9D9F",
                "heading": "#4078f2",
                "code": "#c45b00",
                "link": "#27ae60",
                "quote": "#a626a4",
                "codeBackground": "#0C383A42"
        },
        "Atom One Dark": {
                "background": "#282c34",
                "text": "#abb2bf",
                "selectedText": "#abb2bf",
                "selection": "#363c4a",
                "lineNumber": "#636D83",
                "heading": "#61afef",
                "code": "#c45b00",
                "link": "#27ae60",
                "quote": "#c678dd",
                "codeBackground": "#0A99BBFF"
        },
        "Catppuccin Latte": {
                "background": "#eff1f5",
                "text": "#4c4f69",
                "selectedText": "#4c4f69",
                "selection": "#8cbcc0cc",
                "lineNumber": "#6c6f85",
                "heading": "#1e66f5",
                "code": "#fe640b",
                "link": "#fe640b",
                "quote": "#7287fd",
                "codeBackground": "#ccd0da"
        },
        "Catppuccin Mocha": {
                "background": "#1e1e2e",
                "text": "#cdd6f4",
                "selectedText": "#cdd6f4",
                "selection": "#8c45475a",
                "lineNumber": "#6c7086",
                "heading": "#89b4fa",
                "code": "#fab387",
                "link": "#fab387",
                "quote": "#b4befe",
                "codeBackground": "#66313244"
        },
        "GitHub Light": {
                "background": "#ffffff",
                "text": "#24292e",
                "selectedText": "#24292e",
                "selection": "#dee6fc",
                "lineNumber": "#c7c2bc",
                "heading": "#6f42c1",
                "code": "#6a737d",
                "link": "#6f42c1",
                "quote": "#d73a49",
                "codeBackground": "#f6f8fa"
        },
        "GitHub Dark": {
                "background": "#24292e",
                "text": "#e1e4e8",
                "selectedText": "#e1e4e8",
                "selection": "#253749",
                "lineNumber": "#444d56",
                "heading": "#b392f0",
                "code": "#6a737d",
                "link": "#b392f0",
                "quote": "#f97583",
                "codeBackground": "#2b3036"
        },
        "Solarized Light": {
                "background": "#fdf6e3",
                "text": "#657b83",
                "selectedText": "#839496",
                "selection": "#073642",
                "lineNumber": "#93a1a1",
                "heading": "#268bd2",
                "code": "#b58900",
                "link": "#859900",
                "quote": "#268bd2",
                "codeBackground": "#eee8d5"
        },
        "Solarized Dark": {
                "background": "#002b36",
                "text": "#839496",
                "selectedText": "#586e75",
                "selection": "#083d4a",
                "lineNumber": "#586e75",
                "heading": "#268bd2",
                "code": "#b58900",
                "link": "#859900",
                "quote": "#268bd2",
                "codeBackground": "#073642"
        }
    })
}
