#!/usr/bin/env python3
"""Regenerate kde/src/qml/EditorThemes.qml and core/src/syntax_themes.rs from KDE's syntax-highlighting theme files.

QML cannot read colours from a KSyntaxHighlighting theme (only its name), so the handful of colours the
editor, minimap and preview need are copied here. The token colours for fenced code in the preview
(core/src/syntax_themes.rs) are the same files mapped onto TextMate scopes, so preview == editor. Keep TAG equal to the installed KF6 syntax-highlighting release.
    python3 kde/tools/gen_editor_themes.py
"""
import json, os, urllib.request

TAG = "v6.30.0"
SLUGS = ["breeze-light", "breeze-dark", "atom-one-light", "atom-one-dark", "catppuccin-latte", "catppuccin-mocha",
         "github-light", "github-dark", "solarized-light", "solarized-dark"]
URL = f"https://raw.githubusercontent.com/KDE/syntax-highlighting/{TAG}/data/themes/{{}}.theme"

# KDE text style -> syntect scope selectors. syntect scores each matching selector by how specific it is and
# the most specific wins regardless of order (on an exact tie the earlier rule wins: syntect compares with `>`).
SCOPES = [
    ("Keyword", "keyword, storage, entity.name.tag"),
    ("ControlFlow", "keyword.control"),
    ("Operator", "keyword.operator"),
    ("Import", "keyword.control.import, keyword.other.import"),
    ("Preprocessor", "meta.preprocessor"),
    ("DataType", "support.type, entity.name.type, entity.name.class, entity.name.struct, entity.name.enum, entity.name.trait, entity.other.inherited-class, storage.type.primitive"),
    ("Function", "entity.name.function, support.function, variable.function, markup.heading"),
    ("BuiltIn", "support.function.builtin, support.class, variable.language"),
    ("Variable", "variable.parameter"),
    ("Constant", "constant, support.constant"),
    ("DecVal", "constant.numeric"),
    ("BaseN", "constant.numeric.integer.hexadecimal, constant.numeric.integer.octal, constant.numeric.integer.binary"),
    ("Float", "constant.numeric.float"),
    ("Char", "constant.character"),
    ("SpecialChar", "constant.character.escape"),
    ("String", "string"),
    ("SpecialString", "string.regexp"),
    ("Comment", "comment"),
    ("Documentation", "comment.block.documentation, comment.line.documentation"),
    ("Attribute", "entity.other.attribute-name, markup.quote"),
    ("Annotation", "meta.annotation, storage.type.annotation"),
    ("Information", "markup.raw"),
    ("Others", "markup.underline.link"),
    ("Error", "invalid"),
]

themes, notices, rust = {}, [], []
for slug in SLUGS:
    d = json.load(urllib.request.urlopen(URL.format(slug)))
    ts, ec, meta = d["text-styles"], d["editor-colors"], d["metadata"]
    themes[meta["name"]] = {
        "background": ec["BackgroundColor"],
        "text": ts["Normal"]["text-color"],
        "selectedText": ts["Normal"]["selected-text-color"],
        "selection": ec["TextSelection"],
        "lineNumber": ec["LineNumbers"],
        "heading": ts["Function"]["text-color"],   # Markdown headings use dsFunction
        "code": ts["Information"]["text-color"],   # Markdown code / fenced code use dsInformation
        "link": ts["Others"]["text-color"],        # Markdown auto-links use dsOthers
        "quote": ts["Attribute"]["text-color"],    # Markdown blockquotes use dsAttribute
        "codeBackground": ec["CurrentLine"],       # subtle band, used behind code in the preview
    }
    rules = []
    for key, sel in SCOPES:
        t = ts[key]
        flags = "".join(c for c, k in (("b", "bold"), ("i", "italic"), ("u", "underline")) if t.get(k))
        rules.append(f'        ("{sel}", "{t["text-color"]}", "{flags}"),\n')
    rust.append(f'    ("{meta["name"]}", "{ts["Normal"]["text-color"]}", &[\n' + "".join(rules) + "    ]),\n")
    notices.append(f'//   {meta["name"]}: ' + "; ".join(c.replace("SPDX-FileCopyrightText: ", "") for c in meta["copyright"]))

out = os.path.join(os.path.dirname(__file__), "..", "src", "qml", "EditorThemes.qml")
with open(out, "w") as f:
    f.write(f"// Generated by kde/tools/gen_editor_themes.py from KDE syntax-highlighting {TAG} (data/themes, MIT).\n")
    f.write("// Colours only; token colours come from the library's own theme of the same name. Copyright:\n")
    f.write("\n".join(notices) + "\n")
    f.write("import QtQuick\n\nQtObject {\n    readonly property var themes: (")
    f.write(json.dumps(themes, indent=8).replace("\n}", "\n    }") + ")\n}\n")
print("wrote", out)

out = os.path.join(os.path.dirname(__file__), "..", "..", "core", "src", "syntax_themes.rs")
with open(out, "w") as f:
    f.write(f"// Generated by kde/tools/gen_editor_themes.py from KDE syntax-highlighting {TAG} (data/themes, MIT). Do not edit.\n")
    f.write("// (theme name, normal text colour, [(scope selectors, colour, flags b/i/u)])\n")
    f.write("\n".join(notices) + "\n")
    f.write("pub(crate) type Rules = &'static [(&'static str, &'static str, &'static str)];\n")
    f.write("pub(crate) static THEMES: &[(&str, &str, Rules)] = &[\n" + "".join(rust) + "];\n")
print("wrote", out)
