#!/usr/bin/env python3
"""Regenerate kde/src/qml/EditorThemes.qml from KDE's syntax-highlighting theme files.

QML cannot read colours from a KSyntaxHighlighting theme (only its name), so the handful of colours the
editor, minimap and preview need are copied here. Keep TAG equal to the installed KF6 syntax-highlighting release.
    python3 kde/tools/gen_editor_themes.py
"""
import json, os, urllib.request

TAG = "v6.30.0"
SLUGS = ["breeze-light", "breeze-dark", "atom-one-light", "atom-one-dark", "catppuccin-latte", "catppuccin-mocha",
         "github-light", "github-dark", "solarized-light", "solarized-dark"]
URL = f"https://raw.githubusercontent.com/KDE/syntax-highlighting/{TAG}/data/themes/{{}}.theme"

themes, notices = {}, []
for slug in SLUGS:
    d = json.load(urllib.request.urlopen(URL.format(slug)))
    ts, ec, meta = d["text-styles"], d["editor-colors"], d["metadata"]
    themes[meta["name"]] = {
        "background": ec["BackgroundColor"],
        "text": ts["Normal"]["text-color"],
        "selectedText": ts["Normal"]["selected-text-color"],
        "selection": ec["TextSelection"],
        "lineNumber": ec["LineNumbers"],
        "heading": ts["Function"]["text-color"],   # Markdown headings use dsFunction
        "code": ts["Information"]["text-color"],   # Markdown code / fenced code use dsInformation
        "link": ts["Others"]["text-color"],        # Markdown auto-links use dsOthers
        "quote": ts["Attribute"]["text-color"],    # Markdown blockquotes use dsAttribute
        "codeBackground": ec["CurrentLine"],       # subtle band, used behind code in the preview
    }
    notices.append(f'//   {meta["name"]}: ' + "; ".join(c.replace("SPDX-FileCopyrightText: ", "") for c in meta["copyright"]))

out = os.path.join(os.path.dirname(__file__), "..", "src", "qml", "EditorThemes.qml")
with open(out, "w") as f:
    f.write(f"// Generated by kde/tools/gen_editor_themes.py from KDE syntax-highlighting {TAG} (data/themes, MIT).\n")
    f.write("// Colours only; token colours come from the library's own theme of the same name. Copyright:\n")
    f.write("\n".join(notices) + "\n")
    f.write("import QtQuick\n\nQtObject {\n    readonly property var themes: (")
    f.write(json.dumps(themes, indent=8).replace("\n}", "\n    }") + ")\n}\n")
print("wrote", out)
