// Generated by gnome/tools/gen_gnome_data.py from KDE syntax-highlighting v6.30.0 (data/themes, MIT). Do not edit.
// Colours the preview and the UI take from the editor theme: CSS colours, "#rrggbb" or "rgba(r,g,b,a)".

pub struct Palette {
    pub background: &'static str,
    pub text: &'static str,
    pub heading: &'static str,
    pub code: &'static str,
    pub link: &'static str,
    pub quote: &'static str,
    pub code_background: &'static str,
    pub selection: &'static str,
}

const BREEZE_LIGHT: Palette = Palette {
    background: "#ffffff",
    text: "#1f1c1b",
    heading: "#644a9b",
    code: "#b08000",
    link: "#006e28",
    quote: "#0057ae",
    code_background: "#f8f7f6",
    selection: "#94caef",
};

const BREEZE_DARK: Palette = Palette {
    background: "#232629",
    text: "#cfcfc2",
    heading: "#8e44ad",
    code: "#c45b00",
    link: "#27ae60",
    quote: "#2980b9",
    code_background: "#2A2E32",
    selection: "#2d5c76",
};

const ATOM_ONE_LIGHT: Palette = Palette {
    background: "#fafafa",
    text: "#383a42",
    heading: "#e45649",
    code: "#d19a66",
    link: "#a626a4",
    quote: "#a626a4",
    code_background: "rgba(56,58,66,0.047)",
    selection: "#e5e5e6",
};

const ATOM_ONE_DARK: Palette = Palette {
    background: "#282c34",
    text: "#abb2bf",
    heading: "#e06c75",
    code: "#d19a66",
    link: "#c678dd",
    quote: "#c678dd",
    code_background: "rgba(153,187,255,0.039)",
    selection: "#363c4a",
};

const CATPPUCCIN_LIGHT: Palette = Palette {
    background: "#eff1f5",
    text: "#4c4f69",
    heading: "#1e66f5",
    code: "#40a02b",
    link: "#dc8a78",
    quote: "#40a02b",
    code_background: "#ccd0da",
    selection: "rgba(188,192,204,0.549)",
};

const CATPPUCCIN_DARK: Palette = Palette {
    background: "#1e1e2e",
    text: "#cdd6f4",
    heading: "#89b4fa",
    code: "#a6e3a1",
    link: "#f5e0dc",
    quote: "#a6e3a1",
    code_background: "rgba(49,50,68,0.4)",
    selection: "rgba(69,71,90,0.549)",
};

const GITHUB_LIGHT: Palette = Palette {
    background: "#ffffff",
    text: "#24292e",
    heading: "#6f42c1",
    code: "#6a737d",
    link: "#6f42c1",
    quote: "#d73a49",
    code_background: "#f6f8fa",
    selection: "#dee6fc",
};

const GITHUB_DARK: Palette = Palette {
    background: "#24292e",
    text: "#e1e4e8",
    heading: "#b392f0",
    code: "#6a737d",
    link: "#b392f0",
    quote: "#f97583",
    code_background: "#2b3036",
    selection: "#253749",
};

const SOLARIZED_LIGHT: Palette = Palette {
    background: "#fdf6e3",
    text: "#657b83",
    heading: "#268bd2",
    code: "#b58900",
    link: "#859900",
    quote: "#268bd2",
    code_background: "#eee8d5",
    selection: "#073642",
};

const SOLARIZED_DARK: Palette = Palette {
    background: "#002b36",
    text: "#839496",
    heading: "#268bd2",
    code: "#b58900",
    link: "#859900",
    quote: "#268bd2",
    code_background: "#073642",
    selection: "#083d4a",
};

/// (family slug, light, dark); the first entry is the fallback for unknown families.
const FAMILIES: &[(&str, &Palette, &Palette)] = &[
    ("breeze", &BREEZE_LIGHT, &BREEZE_DARK),
    ("atom-one", &ATOM_ONE_LIGHT, &ATOM_ONE_DARK),
    ("catppuccin", &CATPPUCCIN_LIGHT, &CATPPUCCIN_DARK),
    ("github", &GITHUB_LIGHT, &GITHUB_DARK),
    ("solarized", &SOLARIZED_LIGHT, &SOLARIZED_DARK),
];

fn slug(family: &str) -> String {
    family.trim().to_lowercase().replace(' ', "-")
}

/// The entry for `family` ("Atom One", "atom-one", ...), Breeze when it is unknown.
fn entry(family: &str) -> &'static (&'static str, &'static Palette, &'static Palette) {
    let s = slug(family);
    FAMILIES.iter().find(|e| e.0 == s).unwrap_or(&FAMILIES[0])
}

pub fn palette(family: &str, dark: bool) -> &'static Palette {
    let e = entry(family);
    if dark {
        e.2
    } else {
        e.1
    }
}

/// GtkSourceView scheme id of a family; always one of the installed schemes.
pub fn scheme_id(family: &str, dark: bool) -> String {
    format!(
        "markite-{}-{}",
        entry(family).0,
        if dark { "dark" } else { "light" }
    )
}
