#!/usr/bin/env python3
"""Regenerate the GNOME editor colours from KDE's syntax-highlighting theme files:

  gnome/data/styles/markite-<family>-<light|dark>.xml   GtkSourceView style schemes (10)
  gnome/src/palette.rs                                   the colours the preview and the UI need

Same source, tag and theme list as kde/tools/gen_editor_themes.py, so both editors paint Markdown alike. The
Markdown colours are the theme's `custom-styles.Markdown` entries (markdown.xml item -> default text style when the
theme has no override). Keep TAG equal to the one in the KDE generator. To regenerate (needs network):
    python3 gnome/tools/gen_gnome_data.py
The language definition these schemes colour is hand-written: gnome/data/language-specs/markite-markdown.lang.
"""
import json
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

TAG = "v6.30.0"
SLUGS = ["breeze-light", "breeze-dark", "atom-one-light", "atom-one-dark", "catppuccin-latte", "catppuccin-mocha",
         "github-light", "github-dark", "solarized-light", "solarized-dark"]
URL = "https://raw.githubusercontent.com/KDE/syntax-highlighting/{tag}/data/themes/{slug}.theme"
GENERATED = f"Generated by gnome/tools/gen_gnome_data.py from KDE syntax-highlighting {TAG} (data/themes, MIT). Do not edit."

# markdown.xml item -> (default KDE text style, default flags). markdown.xml's own bold/italic/underline stay in
# force when a theme overrides only the colour (the KDE editor shows italic emphasis under every theme).
MD = {
    "header": ("Header H1", "Function", "b"),
    "horizontal-rule": ("Horizontal Rule", "Normal", "b"),
    "list-marker": ("List", "SpecialString", "b"),
    "list-text": ("List: Normal Text", "Normal", ""),
    "blockquote-marker": ("Blockquote", "Attribute", ""),
    "quote-text": ("Blockquote: Normal Text", "Attribute", ""),
    "code-span": ("Code", "Information", ""),
    "code": ("Code", "Information", ""),
    "fence": ("Fenced Code", "Information", ""),
    "table": ("Table", "Preprocessor", ""),
    "emphasis": ("Emphasis Text", "Normal", "i"),
    "strong-emphasis": ("Strong Text", "Normal", "b"),
    "bold-italic": ("Strong-Emphasis Text", "Normal", "bi"),
    "link-marker": ("Reference-Link", "Comment", ""),
    "link-text": ("Reference-Link Name", "Others", "u"),
    "url": ("Reference-Link: Link", "Comment", "u"),
    "autolink": ("Normal Text: Link", "Normal", "u"),
    "label": ("Reference-Link ID", "Comment", ""),
    "image": ("Inline Image", "Alert", ""),
    "image-url": ("Inline Image: Link", "Alert", "u"),
    "backslash-escape": ("Backslash Escape", "SpecialChar", ""),
    "line-break": ("Line Break", "Normal", "u"),
    "comment": ("Comment", "Comment", ""),
}
# KDE text style -> GtkSourceView default style id.
DEF = [
    ("Comment", "def:comment"), ("Documentation", "def:doc-comment-element"), ("Error", "def:error"),
    ("Alert", "def:note"), ("Warning", "def:warning"), ("String", "def:string"), ("Constant", "def:constant"),
    ("DecVal", "def:decimal"), ("BaseN", "def:base-n-integer"), ("Float", "def:floating-point"),
    ("Char", "def:character"), ("SpecialChar", "def:special-char"), ("Keyword", "def:keyword"),
    ("ControlFlow", "def:statement"), ("DataType", "def:type"), ("Function", "def:function"),
    ("Variable", "def:identifier"), ("BuiltIn", "def:builtin"), ("Preprocessor", "def:preprocessor"),
    ("Others", "def:net-address"), ("Attribute", "def:shebang"),
]


def hexcolor(c):
    """Qt `#AARRGGBB` -> `#RRGGBBAA` (GtkSourceView / CSS order); `#RRGGBB` is returned unchanged."""
    return "#" + c[3:9] + c[1:3] if len(c) == 9 else c


def css(c):
    """CSS colour: `#rrggbb` or, for a Qt `#AARRGGBB`, `rgba(r,g,b,a)`."""
    if len(c) != 9:
        return c
    a, r, g, b = (int(c[i:i + 2], 16) for i in (1, 3, 5, 7))
    return f"rgba({r},{g},{b},{round(a / 255, 3):g})"


def attrs(fg=None, bg=None, flags="", extra=""):
    s = (f' foreground="{hexcolor(fg)}"' if fg else "") + (f' background="{hexcolor(bg)}"' if bg else "")
    for f, name, val in (("b", "bold", "true"), ("i", "italic", "true"), ("u", "underline", "single"), ("s", "strikethrough", "true")):
        s += f' {name}="{val}"' if f in flags else ""
    return s + extra


def flags_of(t, base=""):
    """Flags of a KDE style dict; a key the theme states wins over `base`."""
    out = set(base)
    for f, k in (("b", "bold"), ("i", "italic"), ("u", "underline"), ("s", "strike-through")):
        if k in t:
            (out.add if t[k] else out.discard)(f)
    return "".join(sorted(out))


def fetch(slug):
    with urllib.request.urlopen(URL.format(tag=TAG, slug=slug), timeout=30) as resp:
        return json.load(resp)


def scheme(slug, d, family_slug, dark):
    ts, ec, meta = d["text-styles"], d["editor-colors"], d["metadata"]
    md = d.get("custom-styles", {}).get("Markdown", {})
    normal = ts["Normal"]["text-color"]
    pair = f"markite-{family_slug}-{'light' if dark else 'dark'}"
    link = "light-variant" if dark else "dark-variant"
    rows = [
        ("text", attrs(normal, ec["BackgroundColor"])),
        ("cursor", attrs(normal)),
        ("line-numbers", attrs(ec["LineNumbers"], ec["BackgroundColor"])),
        ("current-line", attrs(bg=ec["CurrentLine"])),
        ("current-line-number", attrs(ec["CurrentLineNumber"], ec["CurrentLine"])),
        ("selection", attrs(bg=ec["TextSelection"])),
        ("search-match", attrs(bg=ec["SearchHighlight"])),
        ("map-overlay", attrs(bg=ec["TextSelection"])),
        ("bracket-match", attrs(bg=ec["BracketMatching"], flags="b")),
        ("right-margin", attrs(ec["WordWrapMarker"], ec["WordWrapMarker"])),
        ("draw-spaces", attrs(ec["TabMarker"])),
    ]
    for kde, gsv in DEF:
        t = ts[kde]
        rows.append((gsv, attrs(t["text-color"], flags=flags_of(t).replace("u", ""),
                                extra=' underline="error"' if gsv == "def:error" else "")))
    # Generic Markdown ids other languages also use; the Markdown language maps its own ids onto these as fallback.
    for gsv, item in (("def:heading", "header"), ("def:list-marker", "list-marker"), ("def:inline-code", "code-span"),
                      ("def:preformatted-section", "code"), ("def:thematic-break", "horizontal-rule"),
                      ("def:link-text", "link-text"), ("def:link-destination", "url"),
                      ("def:emphasis", "emphasis"), ("def:strong-emphasis", "strong-emphasis")):
        rows.append((gsv, md_attrs(md, ts, item)))
    for item in MD:
        rows.append((f"markite-markdown:{item}", md_attrs(md, ts, item)))
    body = "\n".join(f'  <style name="{n}"{a}/>' for n, a in rows)
    return (f'<?xml version="1.0" encoding="UTF-8"?>\n<!-- {GENERATED}\n     Colours: {"; ".join(c.replace("SPDX-FileCopyrightText: ", "") for c in meta["copyright"])} ({meta["license"].replace("SPDX-License-Identifier: ", "")}) -->\n'
            f'<style-scheme id="markite-{family_slug}-{"dark" if dark else "light"}" name="{meta["name"]}" version="1.0">\n'
            f'  <author>Markite</author>\n  <description>{meta["name"]}, from KDE syntax-highlighting</description>\n'
            f'  <metadata>\n    <property name="variant">{"dark" if dark else "light"}</property>\n'
            f'    <property name="{link}">{pair}</property>\n  </metadata>\n{body}\n</style-scheme>\n')


def md_attrs(md, ts, item):
    name, style, base = MD[item]
    t = md.get(name, {})
    return attrs(t.get("text-color") or ts[style]["text-color"], flags=flags_of(t, base))


def md_color(md, ts, item):
    name, style, _ = MD[item]
    return md.get(name, {}).get("text-color") or ts[style]["text-color"]


def link_color(md, ts):
    """The plain `Link` style, for links in the preview."""
    return md.get("Link", {}).get("text-color") or ts["Others"]["text-color"]


themes = {}
for slug in SLUGS:
    d = fetch(slug)
    family_slug, variant = slug.rsplit("-", 1)
    dark = variant in ("dark", "mocha")  # Catppuccin names its variants after flavours
    slug = f"{family_slug}-{'dark' if dark else 'light'}"
    out = ROOT / f"gnome/data/styles/markite-{slug}.xml"
    out.write_text(scheme(slug, d, family_slug, dark), encoding="utf-8")
    print("wrote", out)
    ts, ec = d["text-styles"], d["editor-colors"]
    md = d.get("custom-styles", {}).get("Markdown", {})
    themes[slug] = dict(
        background=ec["BackgroundColor"], text=ts["Normal"]["text-color"], heading=md_color(md, ts, "header"),
        code=md_color(md, ts, "code"), link=link_color(md, ts), quote=md_color(md, ts, "quote-text"),
        code_background=ec["CurrentLine"], selection=ec["TextSelection"])

consts = []
for slug, p in themes.items():
    fields = ",\n".join(f'    {k}: "{css(v)}"' for k, v in p.items())
    consts.append(f"const {slug.upper().replace('-', '_')}: Palette = Palette {{\n{fields},\n}};\n")
families = sorted({s.rsplit("-", 1)[0] for s in themes}, key=lambda f: (f != "breeze", f))
table = "".join(
    f'    ("{f}", &{f.upper().replace("-", "_")}_LIGHT, &{f.upper().replace("-", "_")}_DARK),\n' for f in families)
(ROOT / "gnome/src/palette.rs").write_text(f"""// {GENERATED}
// Colours the preview and the UI take from the editor theme: CSS colours, "#rrggbb" or "rgba(r,g,b,a)".

pub struct Palette {{
    pub background: &'static str,
    pub text: &'static str,
    pub heading: &'static str,
    pub code: &'static str,
    pub link: &'static str,
    pub quote: &'static str,
    pub code_background: &'static str,
    pub selection: &'static str,
}}

""" + "\n".join(consts) + f"""
/// (family slug, light, dark); the first entry is the fallback for unknown families.
const FAMILIES: &[(&str, &Palette, &Palette)] = &[
{table}];

fn slug(family: &str) -> String {{
    family.trim().to_lowercase().replace(' ', "-")
}}

/// The entry for `family` ("Atom One", "atom-one", ...), Breeze when it is unknown.
fn entry(family: &str) -> &'static (&'static str, &'static Palette, &'static Palette) {{
    let s = slug(family);
    FAMILIES.iter().find(|e| e.0 == s).unwrap_or(&FAMILIES[0])
}}

pub fn palette(family: &str, dark: bool) -> &'static Palette {{
    let e = entry(family);
    if dark {{
        e.2
    }} else {{
        e.1
    }}
}}

/// GtkSourceView scheme id of a family; always one of the installed schemes.
pub fn scheme_id(family: &str, dark: bool) -> String {{
    format!(
        "markite-{{}}-{{}}",
        entry(family).0,
        if dark {{ "dark" }} else {{ "light" }}
    )
}}
""", encoding="utf-8")
print("wrote gnome/src/palette.rs")
